this.__phrases__ = {
	'month_1': 'january',
	'month_2': 'february',
	'month_3': 'march',
	'month_4': 'april',
	'month_5': 'mayb',
	'month_6': 'june',
	'month_7': 'july',
	'month_8': 'august',
	'month_9': 'september',
	'month_10': 'october',
	'month_11': 'november',
	'month_12': 'december',
	'Month_1': 'January',
	'Month_2': 'February',
	'Month_3': 'March',
	'Month_4': 'April',
	'Month_5': 'May',
	'Month_6': 'June',
	'Month_7': 'July',
	'Month_8': 'August',
	'Month_9': 'September',
	'Month_10': 'October',
	'Month_11': 'November',
	'Month_12': 'December',
	'week_day_1': 'monday',
	'week_day_2': 'tuesday',
	'week_day_3': 'wednesday',
	'week_day_4': 'thursday',
	'week_day_5': 'friday',
	'week_day_6': 'saturday',
	'week_day_7': 'sunday',
	'Week_day_1': 'Monday',
	'Week_day_2': 'Tuesday',
	'Week_day_3': 'Wednesday',
	'Week_day_4': 'Thursday',
	'Week_day_5': 'Friday',
	'Week_day_6': 'Saturday',
	'Week_day_7': 'Sunday',
	'ACCEPT': 'The operation was completed successfully. No errors were detected.',
	'SYNTAX': "The error was detected when you tried to run the operation with syntactic function. You can't fix it, contact support, or use the help information.",
	'INCLUDER_LIST': 'A fatal error occurred when connecting a list of third-party resources. Some resources were not loaded, please do this manually. If the error is not caused by you, write to support or use the error correction instructions.',
	'TIME_SCHEME': 'There are problems is in the Time Scheme. Use the guide to edit the Time Scheme.',
	'LANG_DETECT': 'Error when trying to determine your language. Please install a newer browser. Try installing the latest version of Google Chrome.',
	'SIZES': 'Error when trying to determine some dimensional characteristics. You may need a newer browser. Try installing the latest version of Google Chrome.',
	'ADAPTIVITY_DEVICE': "Error when trying to detect your device. If you don't mind installing a newer browser. The latest version of Google Chrome may be suitable for you.",
	'open_sj': 'You have enabled StupidJoke.',
	'script_list': 'The list of scripts that were successfully imported.'
};